files:
  - source: /*.csv
    translation: '%original_file_name%'
    first_line_contains_header: 1
    scheme: 'identifier,context,source_phrase,es-ES,fr,max_length'
    multilingual: 1
bundles:
  - 5
