files:
  - source: /*.xlsx
    translation: /%two_letters_code%/%original_file_name%
    multilingual: 1
    first_line_contains_header: 1
    scheme: 'identifier,context,source_phrase,es-ES,fr,max_length'
